### ISSUE TITLE
[BUG] SLO not working correctly, cookies not removed

### ISSUE THREAD

**Issue by wknopki** [keitaroinc/ckanext-saml2auth#68] opened 2022-06-21 12:05 UTC
**Describe the bug**
Upon logging the user out (either via IDP-initiated logout or via SP-initiated Logout) the session remains, although the IdP reports a clear logout.

The Binding used for logout is 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'

This appears to be related to #55 , #56 and #58, because the auth_tkt and ckan cookies do not get deleted.

The behaviour was tested in firefox (100.0.2) and chromium (91.0.4472.27) browsers.

**ckanext-saml2auth version affected**
v1.2.2

**Expected behaviour**
User is logged out and the auth_tkt and ckan cookies get deleted

**Further info**
The following hack 'solves' the problem:

```

diff --git a/ckanext/saml2auth/plugin.py b/ckanext/saml2auth/plugin.py
index 83f703b..c153f37 100644
--- a/ckanext/saml2auth/plugin.py
+++ b/ckanext/saml2auth/plugin.py
@@ -103,7 +103,7 @@ class Saml2AuthPlugin(plugins.SingletonPlugin):
             domain = h.get_site_domain_for_cookie()
 
             # Clear auth cookie in the browser
-            response.set_cookie('auth_tkt', domain=domain, expires=0)
+            response.set_cookie('auth_tkt', expires=0)
 
             # Clear session cookie in the browser
             response.set_cookie('ckan', domain=domain, expires=0)
```

This can in my opinion not be seen as a solution, because it indiscriminantly removes all auth_tkt cookies, so I would appreciate, if someone with more in-depth knowledge looks into a real solution.

**Comment by duskobogdanovski** [comment] 2022-07-01 09:56
Hey @wknopki, we will take look at this.

**Comment by iAce02** [comment] 2022-07-13 15:09
Hello @wknopki . 
We looked and tested this , but we couldn't replicate the issue, everything works as expected. Ckan cookies are expiring after the user is logged out. Please check and confirm the configuration and if you are still encountering this issue, provide more info ( how and where did you setup the integration)

**Comment by wknopki** [comment] 2022-07-15 11:41
Hello @iAce02 , 

thanks for looking into the issue.

As for the integration, here are the relevant parts of my ckan.ini:

```
## Site Settings

ckan.site_url = https://m4lab.hft-stuttgart.de/
ckan.root_path = /katalog/{{LANG}}

ckanext.saml2auth.idp_metadata.location = remote

ckanext.saml2auth.idp_metadata.remote_url = https://transfer.hft-stuttgart.de/idp2/saml2/idp/metadata.php

ckanext.saml2auth.idp_metadata.remote_cert = /opt/certs/certidpmd.cert

ckanext.saml2auth.user_firstname = givenName
ckanext.saml2auth.user_lastname = sn
ckanext.saml2auth.user_email = mail

ckanext.saml2auth.acs_endpoint = /acs

ckanext.saml2auth.logout_expected_binding =  urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect

```
Ckan is running behind a reverse proxy, here are the relevant entries in nginx' config:

```
location /katalog/ {
        proxy_pass http://127.0.0.1:8080/;
        proxy_set_header Host $host;
   }
   location /acs {
        proxy_pass http://127.0.0.1:8080/acs;
        proxy_set_header Host $host;
   }
   location /slo {
        proxy_pass http://127.0.0.1:8080/slo;
        proxy_set_header Host $host;
   }
   location /user/ {
        proxy_pass http://127.0.0.1:8080/user/;
        proxy_set_header Host $host;
   }
   location /base/ {
        proxy_pass http://127.0.0.1:8080/base/;
        proxy_set_header Host $host;
   }
```

On a logout, the browser is still (currently on commit 85a9a3bdd88e944aa6862eb4508a0d3eab46dfcd ) showing an error page claiming "too many redirects"

**Comment by duskobogdanovski** [comment] 2022-11-08 14:09
Closing this for now since it can't be reproduced.

**Closed by duskobogdanovski** 2022-11-08 14:09 UTC
