### ISSUE TITLE
[BUG] ckanext-saml2auth with Keycloak - How define client id (issuer / entity)

### ISSUE THREAD

**Issue by BPMCRA** [keitaroinc/ckanext-saml2auth#62] opened 2021-10-25 16:52 UTC
Hi,
I installed the ckanext-saml2auth module under CKAN 2.9 in order to interface with Keycloak. I can't find a way to specify the id of the client on which the request should be sent.

When I use the connection button via CKAN, I am directed to Keycloak but the latter receives the following message:

2021-10-25 16:05:10,095 WARN  [org.keycloak.events] (default task-218) type=LOGIN_ERROR, realmId=MYREALM, clientId=null, userId=null, ipAddress=myaddress.com, error=client_not_found, reason=Cannot_match_source_hash

I'm trying to use ckanext.saml2auth.entity_id but it seems not working for me.

**Comment by duskobogdanovski** [comment] 2022-01-12 15:17
Closing this issue for now because it can not be reproduced.

**Closed by duskobogdanovski** 2022-01-12 15:17 UTC
